stages:
  - build
  - deploy

# before_script:
#   - docker info

build:
  stage: build
  services:
    - docker:20.10.16-dind
  script:
    - docker login --username iam --password-stdin cr.yandex < $REGISTRY_IAM_TOKEN
    - docker build -f dockerfiles/Dockerfile_server -t cr.yandex/crpa8gap9g6vl6hshofn/olzhas_grpc_server_test1:gitlab-$CI_COMMIT_SHORT_SHA .
    - docker push cr.yandex/crpa8gap9g6vl6hshofn/grpc-server:gitlab-$CI_COMMIT_SHORT_SHA

deploy:
  image: cr.yandex/crpa8gap9g6vl6hshofn/builder:latest
  stage: deploy
  script:
    - kubectl config set-cluster k8s --server="$KUBE_URL" --insecure-skip-tls-verify=true
    - kubectl config set-credentials admin --token="$KUBE_TOKEN"
    - kubectl config set-context default --cluster=k8s --user=admin
    - kubectl config use-context default
    - sed -i "s/__VERSION__/gitlab-$CI_COMMIT_SHORT_SHA/" k8s.yaml
    - kubectl apply -f k8s.yaml
