FROM golang:1.17-alpine

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . ./
RUN CGO_ENABLED=0 go build -o /server cmd/server/main.go

#FROM golang:1.17
#
#WORKDIR /
#
#COPY --from=build /server /server
#
#COPY /config.yaml /config.yaml
EXPOSE 8080
ENTRYPOINT ["/server"]
