FROM golang:1.17

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . ./

RUN CGO_ENABLED=0 go build -o /client cmd/client/main.go

#FROM golang:1.17
#
#WORKDIR /
#
#COPY --from=build /client /client
#
#COPY /config.yaml /config.yaml
EXPOSE 8081
ENTRYPOINT ["/client"]